from setuptools import setup, find_packages

setup(
    name="calorieApp_server",
    version="4.0.0",
    packages=find_packages(),
    install_requires=[
        "aiohttp==3.9.0",
        "aiosignal==1.3.1",
        "annotated-types==0.6.0",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.1.0",
        "bcrypt==4.0.1",
        "blinker==1.6.2",
        "certifi==2023.7.22",
        "cffi==1.15.1",
        "charset-normalizer==3.3.2",
        "click==8.1.7",
        "colorama==0.4.6",
        "cryptography==41.0.3",
        "dataclasses-json==0.6.2",
        "distro==1.8.0",
        "dnspython==2.4.2",
        "email-validator==2.0.0.post2",
        "exceptiongroup==1.2.0",
        "Flask==2.3.3",
        "Flask-Login==0.6.2",
        "Flask-Mail==0.9.1",
        "Flask-PyMongo==2.3.0",
        "Flask-WTF==1.1.1",
        "frozenlist==1.4.0",
        "h11==0.14.0",
        "httpcore==1.0.2",
        "httpx==0.25.2",
        "idna==3.4",
        "iniconfig==2.0.0",
        "itsdangerous==2.1.2",
        "Jinja2==3.1.2",
        "jsonpatch==1.33",
        "jsonpointer==2.4",
        "jwt==1.3.1",
        "langchain==0.0.340",
        "langsmith==0.0.66",
        "MarkupSafe==2.1.3",
        "marshmallow==3.20.1",
        "multidict==6.0.4",
        "mypy-extensions==1.0.0",
        "numpy==1.26.2",
        "openai==1.3.5",
        "packaging==23.2",
        "pathspec==0.11.2",
        "platformdirs==4.0.0",
        "pluggy==1.3.0",
        "pycparser==2.21",
        "pydantic==2.5.2",
        "pydantic_core==2.14.5",
        "pymongo==4.5.0",
        "python-dateutil==2.8.2",
        "python-dotenv==1.0.0",
        "PyYAML==6.0.1",
        "regex==2023.10.3",
        "requests==2.31.0",
        "six==1.16.0",
        "sniffio==1.3.0",
        "SQLAlchemy==2.0.23",
        "tabulate==0.9.0",
        "tenacity==8.2.3",
        "tiktoken==0.5.1",
        "tomli==2.0.1",
        "tqdm==4.66.1",
        "typing-inspect==0.9.0",
        "typing_extensions==4.8.0",
        "urllib3==2.1.0",
        "Werkzeug==2.3.7",
        "WTForms==3.0.1",
        "yarl==1.9.3",
    ],
    entry_points={
        "console_scripts": [
            "run-server = src.application:run_server",
        ],
    },
    author="Benyamin Tabarsi, Keith Tran, Kimia Fazeli, Mohammed Faizan",
    author_email="ktran24@ncsu.edu",
    description="BurnOut: Fuel Your Fitness Journey!",
    url="https://github.com/tran4code/calorieApp_server",
    long_description=open("README.md", "r").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    license="MIT",
    python_requires=">=3.10",
)
